config/routes.rb
Rails.application.routes.draw do

  root 'home#index'


  get 'accounts/register',to: 'accounts#register', as: 'register'
  get 'accounts/login',to: 'accounts#login', as: 'login'


  get '/customer', to: 'home#customer', as: 'customer'
  get '/about', to: 'home#about', as: 'about'
  
  post '/submit', to: 'home#addCustomer'
  delete 'customer/:id', to: 'home#delete', as: 'delete'




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord

    attribute :firstname,:string
    attribute :lastname, :string
    attribute :email, :string
    attribute :job, :string
    attribute :description, :string

    validates :firstname, presence: true
    validates :lastname, presence: true
    validates :email, presence: true
    validates :job, presence: true
    validates :description, presence: true

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def register
  end

  def login
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

# GET ALL CUSTOMERS

def customer
  @customers = Customer.all

end


def about
  puts "this is the about page"

end


def delete
  customer = Customer.find(params[:id])
  customer.delete
  puts "deleted successfully"
  redirect_to root_path, notice: 'Customer was successfully deleted.'

end


  def addCustomer
    first_name = params[:fname]
    last_name = params[:lname]
    email = params[:email]
    job = params[:job]
    description = params[:description]

    customer = Customer.new(firstname: first_name, lastname: last_name, email: email, job: job, description: description)

    if customer.save
      redirect_to root_path, notice: 'Customer was successfully created.'
    
    else
      redirect_to root_path, alert: 'Failed to create customer.'
    end
    
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/accounts/login.html.erb
<h1>Accounts#login</h1>
<p>Find me in app/views/accounts/login.html.erb</p>

app/views/accounts/register.html.erb
<h1>Accounts#register</h1>
<p>Find me in app/views/accounts/register.html.erb</p>

app/views/home/about.html.erb
<%= render 'shared/navbar' %>

<div class="container">
    <span>This is the about page</span>
</div>

app/views/home/customer.html.erb
<%= render 'shared/navbar' %>


<div class ="container mt-5">
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Job</th>
      <th scope="col">Email</th>
       <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.firstname %></td>
        <td><%= customer.lastname %></td>
         <td><%= customer.job %></td>
          <td><%= customer.email %></td>
          <td><%= link_to 'delete', customer_path(customer), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/home/index.html.erb
<%= render 'shared/navbar' %>
<div class="container mt-5">
    <h1 class="text-center">Customer Registration</h1>

    <div>
    <%= form_with url: '/submit', method: :post do |form| %>
    <div class="mb-3">
        <%= form.label :first_name %>
        <%= form.text_field :fname, class: 'form-control' %>
    </div>

    <div class="mb-3">
        <%= form.label :last_name %>
        <%= form.text_field :lname, class: 'form-control' %>
    </div>
    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: 'form-control' %>
    </div>
    <div class="mb-3">
        <%= form.label :job %>
        <%= form.text_field :job, class: 'form-control' %>
    </div>
    <div class="mb-3">
        <%= form.label :description %>
        <%= form.text_area  :description, class: 'form-control' %>
    </div>

    <%= form.submit "Submit", class: 'btn btn-primary form-control' %>
    <%end%>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployerRegistration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav mx-auto">
        <%= link_to "home", root_path, class: 'nav-link active' %>
        <%= link_to "customer", customer_path, class: 'nav-link' %>
        <%= link_to "about", about_path, class: 'nav-link' %>
      </div>

      <div class="navbar-nav">
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Accounts
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "register", register_path, class: 'dropdown-item' %></li>
            <li><%= link_to "login", login_path, class: 'dropdown-item' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>